---
title: "About Me"
---

Hello Everyone! 

I am currently a Case PREP scholar, here at Case Western Reserve University. I got my undergraduate degree in Biology (B.S.). I decided to pursue this post-bas oppurtunity because I wanted to pursue biomedical research instead of entomology research. A lot of my prior research experiences had been entomology based, and I realized I needed more training. I am super excited to have this oppunruintiy and be able to expand my knowledge of all things research! 

Here's a quick blurb of my personal statement just to tell you more about who I am, and why I want a Ph.D.! 
 
 "As a first-generation, biracial student with bilateral hearing loss, my personal experiences with healthcare have fueled my commitment to biomedical research that informs prevention and treatment strategies, particularly for underrepresented populations. Upon completing my PhD, I aim to lead research utilizing data-driven approaches to address healthcare disparities and improve patient outcomes."
 
 Being a first-generation student has awalys been such a huge portion of my life and my identity. In addition, being a biracial student with a disability, I hope to one day be an inspiration for others. :) 


